{{- if .Values.registryCredentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registryCredentials.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "registry.imagePullSecret" . }}
{{- end }}
{{- if .Values.global.prepuller.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registryCredentials.secretName }}
  namespace: {{ .Values.global.prepuller.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "registry.imagePullSecret" . }}
{{- end }}
{{- if and (.Values.global.ingress.tls.wildcard.tlsSecret.certificate) (.Values.global.ingress.tls.wildcard.tlsSecret.key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wildcard-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.ingress.tls.wildcard.tlsSecret.certificate }}
  tls.key: {{ .Values.global.ingress.tls.wildcard.tlsSecret.key }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: truststore
  labels:
    {{- include "suite.labels" . | nindent 4 }}
    {{- if len .Values.global.commonLabels }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.global.truststore }}
  {{ $key }}: {{ tpl $value $ }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: additional-configuration-files
  labels:
    {{- include "suite.labels" . | nindent 4 }}
    {{- if len .Values.global.commonLabels }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
    {{- end }}
data:
{{- range $key, $value := .Values.global.additionalConfigurationFiles }}
  {{ $key }}: {{ tpl $value $ }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kerberos-config
  labels:
    {{- include "suite.labels" . | nindent 4 }}
    {{- if len .Values.global.commonLabels }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
    {{- end }}
data:
  krb5.conf: {{ .Values.global.krb5Conf | b64enc }}
  {{- if len .Values.global.keytab }}
  krb5.keytab: {{ .Values.global.keytab }}
  {{- end }}