
replicaCount: 1
fullnameOverride: "redis"

kind: StatefulSet

podManagementPolicy: OrderedReady

image:
  registry: "docker.io"
  repository: redis
  tag: ""
  digest: ""

nameOverride: ""

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
    ephemeral-storage: "128Mi"
  limits:
    memory: "2Gi"
    cpu: "1"
    ephemeral-storage: "128Mi"

additionalVolumeMounts: []

command: []

additionalVolumes: []

autoscaling:
  enabled: false

springApplicationJson:
  enabled: false

configMap:
  enabled: false

extraEnv:
  TZ: "{{ .Values.global.timezone }}"

serviceAccount:
  create: false

persistentVolume:
  enabled: false

strategy: {}

podAnnotations: {}

tolerations: {}

nodeSelector: {}

affinity: {}

healthProbes:
  lifecycle:
    postStart:
      exec:
        command:
          - redis-cli 
          - CONFIG 
          - SET 
          - save
          - ""
  readinessProbe:
    exec:
      command:
      - redis-cli
      - ping
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 2
  livenessProbe:
    exec:
      command:
      - redis-cli
      - --raw
      - incr
      - live
    failureThreshold: 5
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 6

fluentBitSidecar:
  enabled: false

extraSidecars: []

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  headless: 
    enabled: false
