apiVersion: v2
name: suite
description: Platform Helm Chart
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

dependencies:
  - name: tika
    version: 3.1.0
    condition: tika.enabled
  - name: redis
    version: 8.0.2
    condition: redis.enabled
  - name: opensearch
    version: 2.19.1
    condition: opensearch.enabled
  - name: postgresql
    version: 12.3.1
    condition: postgresql.enabled
  - name: kafka
    version: 3.9.0
    condition: kafka.enabled
  - name: rabbitmq
    version: 4.1.1
    condition: rabbitmq.enabled
